import { components } from 'src/dpr/types/api'

export const multiselectExample: components['schemas']['VariantDefinition'] = {
  id: 'multiselectExample',
  name: 'Multiselect',
  description: 'Multiselect example',
  resourceName: 'reports/list',
  classification: 'OFFICIAL',
  printable: false,
  specification: {
    sections: [],
    template: 'list',
    fields: [
      {
        name: 'field1',
        display: 'Mutliselect',
        sortable: false,
        visible: true,
        type: 'string',
        mandatory: false,
        calculated: false,
        header: false,
        defaultsort: false,
        filter: {
          mandatory: false,
          type: 'multiselect',
          staticOptions: [
            { name: 'value1', display: 'Value 1' },
            { name: 'value2', display: 'Value 2' },
            { name: 'value3', display: 'Value 3' },
            { name: 'value4', display: 'Value 4' },
            { name: 'value5', display: 'Value 5' },
            { name: 'value6', display: 'Value 6' },
            { name: 'value7', display: 'Value 7' },
            { name: 'value8', display: 'Value 8' },
            { name: 'value9', display: 'Value 9' },
            { name: 'value10', display: 'Value 10' },
            { name: 'value11', display: 'Value 11' },
            { name: 'value12', display: 'Value 12' },
            { name: 'value13', display: 'Value 13' },
            { name: 'value14', display: 'Value 14' },
            { name: 'value15', display: 'Value 15' },
            { name: 'value16', display: 'Value 16' },
          ],
          defaultValue: 'value1,value2',
          interactive: true,
        },
      },
      {
        name: 'field2',
        display: 'Field 2',
        sortable: true,
        defaultsort: true,
        type: 'string',
        mandatory: false,
        visible: true,
        calculated: false,
        header: false,
        filter: {
          type: 'Radio',
          staticOptions: [
            { name: 'value1.1', display: 'Value 1.1' },
            { name: 'value1.2', display: 'Value 1.2' },
            { name: 'value1.3', display: 'Value 1.3' },
          ],
          defaultValue: 'value1.2',
          mandatory: false,
          interactive: true,
        },
      },
      {
        name: 'field3',
        display: 'Field 3',
        sortable: true,
        type: 'string',
        mandatory: true,
        visible: true,
        calculated: false,
        header: false,
        defaultsort: false,
        filter: {
          type: 'Select',
          staticOptions: [
            { name: 'value2.1', display: 'Value 2.1' },
            { name: 'value2.2', display: 'Value 2.2' },
            { name: 'value2.3', display: 'Value 2.3' },
          ],
          mandatory: false,
          interactive: true,
        },
      },
      {
        name: 'field4',
        display: 'Mutliselect 2',
        sortable: false,
        visible: true,
        type: 'string',
        mandatory: false,
        calculated: false,
        header: false,
        defaultsort: false,
        filter: {
          mandatory: false,
          type: 'multiselect',
          staticOptions: [
            { name: 'value1', display: 'Value 1' },
            { name: 'value2', display: 'Value 2' },
            { name: 'value3', display: 'Value 3' },
            { name: 'value4', display: 'Value 4' },
            { name: 'value5', display: 'Value 5' },
            { name: 'value6', display: 'Value 6' },
            { name: 'value7', display: 'Value 7' },
            { name: 'value8', display: 'Value 8' },
            { name: 'value9', display: 'Value 9' },
            { name: 'value10', display: 'Value 10' },
            { name: 'value11', display: 'Value 11' },
            { name: 'value12', display: 'Value 12' },
            { name: 'value13', display: 'Value 13' },
            { name: 'value14', display: 'Value 14' },
            { name: 'value15', display: 'Value 15' },
            { name: 'value16', display: 'Value 16' },
          ],
          defaultValue: 'value1,value2',
          interactive: true,
        },
      },
      {
        name: 'field5',
        display: 'Mutliselect 3',
        sortable: false,
        visible: true,
        type: 'string',
        mandatory: false,
        calculated: false,
        header: false,
        defaultsort: false,
        filter: {
          mandatory: false,
          type: 'multiselect',
          staticOptions: [
            { name: 'value1', display: 'Value 1' },
            { name: 'value2', display: 'Value 2' },
            { name: 'value3', display: 'Value 3' },
            { name: 'value4', display: 'Value 4' },
            { name: 'value5', display: 'Value 5' },
            { name: 'value6', display: 'Value 6' },
            { name: 'value7', display: 'Value 7' },
            { name: 'value8', display: 'Value 8' },
            { name: 'value9', display: 'Value 9' },
            { name: 'value10', display: 'Value 10' },
            { name: 'value11', display: 'Value 11' },
            { name: 'value12', display: 'Value 12' },
            { name: 'value13', display: 'Value 13' },
            { name: 'value14', display: 'Value 14' },
            { name: 'value15', display: 'Value 15' },
            { name: 'value16', display: 'Value 16' },
          ],
          defaultValue: 'value1,value2',
          interactive: false,
        },
      },
    ],
  },
}
