import { components } from 'dpr/types/api'

export const variant34: components['schemas']['VariantDefinition'] = {
  id: 'variantId-34',
  name: 'Sectioned row - Incident report',
  description: 'An example of an incident report using a row section template.',
  resourceName: 'reports/list',
  classification: 'OFFICIAL',
  printable: true,
  specification: {
    template: 'row-section-child',
    sections: ['section1', 'section2', 'section3', 'section4'],
    fields: [
      {
        name: 'type',
        display: 'Type',
        sortable: false,
        defaultsort: false,
        type: 'string',
        mandatory: false,
        visible: true,
        calculated: false,
        header: false,
      },
      {
        name: 'date',
        display: 'Date and time of incident',
        sortable: false,
        defaultsort: false,
        type: 'string',
        mandatory: false,
        visible: true,
        calculated: false,
        header: false,
      },
      {
        name: 'status',
        display: 'Status',
        sortable: false,
        defaultsort: false,
        type: 'string',
        mandatory: false,
        visible: true,
        calculated: false,
        header: false,
      },
      {
        name: 'reportedBy',
        display: 'Reported by',
        sortable: false,
        defaultsort: false,
        type: 'string',
        mandatory: false,
        visible: true,
        calculated: false,
        header: false,
      },
      {
        name: 'description',
        display: 'Description',
        sortable: false,
        defaultsort: false,
        type: 'string',
        mandatory: false,
        visible: true,
        calculated: false,
        header: false,
      },
      {
        name: 'joinField',
        display: 'Join Field',
        sortable: false,
        defaultsort: false,
        type: 'string',
        mandatory: false,
        visible: false,
        calculated: false,
        header: false,
      },
      {
        name: 'section1',
        display: 'Incident Summary',
        sortable: false,
        defaultsort: false,
        type: 'string',
        mandatory: false,
        visible: false,
        calculated: false,
        header: false,
      },
      {
        name: 'section2',
        display: 'Prisoners involved',
        sortable: false,
        defaultsort: false,
        type: 'string',
        mandatory: false,
        visible: false,
        calculated: false,
        header: false,
      },
      {
        name: 'section3',
        display: 'Staff involved',
        sortable: false,
        defaultsort: false,
        type: 'string',
        mandatory: false,
        visible: false,
        calculated: false,
        header: false,
      },
      {
        name: 'section4',
        display: 'About the incident',
        sortable: false,
        defaultsort: false,
        type: 'string',
        mandatory: false,
        visible: false,
        calculated: false,
        header: false,
      },
    ],
  },
  childVariants: [
    {
      id: 'variantId-34-prisoners-involved',
      name: 'Child Report',
      resourceName: 'reports/list',
      joinFields: ['incidentId'],
      specification: {
        sections: [],
        template: 'row-section-child',
        fields: [
          {
            name: 'prisonerName',
            display: 'Child field 1',
            sortable: false,
            defaultsort: false,
            type: 'string',
            mandatory: false,
            visible: true,
            calculated: false,
            header: false,
          },
          {
            name: 'prisonerDetails',
            display: 'Child field 2',
            sortable: false,
            defaultsort: false,
            type: 'string',
            mandatory: false,
            visible: true,
            calculated: false,
            header: false,
          },
          {
            name: 'incidentId',
            display: 'Join Field',
            sortable: false,
            defaultsort: false,
            type: 'string',
            mandatory: false,
            visible: false,
            calculated: false,
            header: false,
          },
        ],
      },
    },
    {
      id: 'variantId-34-staff-involved',
      name: 'Child Report',
      resourceName: 'reports/list',
      joinFields: ['incidentId'],
      specification: {
        sections: [],
        template: 'row-section-child',
        fields: [
          {
            name: 'staffName',
            display: 'Child field 1',
            sortable: false,
            defaultsort: false,
            type: 'string',
            mandatory: false,
            visible: true,
            calculated: false,
            header: false,
          },
          {
            name: 'staffDetails',
            display: 'Child field 2',
            sortable: false,
            defaultsort: false,
            type: 'string',
            mandatory: false,
            visible: true,
            calculated: false,
            header: false,
          },
          {
            name: 'incidentId',
            display: 'Join Field',
            sortable: false,
            defaultsort: false,
            type: 'string',
            mandatory: false,
            visible: false,
            calculated: false,
            header: false,
          },
        ],
      },
    },
    {
      id: 'variantId-34-incident-details',
      name: 'Child Report',
      resourceName: 'reports/list',
      joinFields: ['incidentId'],
      specification: {
        sections: [],
        template: 'row-section-child',
        fields: [
          {
            name: 'incidentQuestion',
            display: 'Incident Question',
            sortable: false,
            defaultsort: false,
            type: 'string',
            mandatory: false,
            visible: true,
            calculated: false,
            header: false,
          },
          {
            name: 'incidentResponse',
            display: 'Incident Response',
            sortable: false,
            defaultsort: false,
            type: 'string',
            mandatory: false,
            visible: true,
            calculated: false,
            header: false,
          },
          {
            name: 'incidentId',
            display: 'Join Field',
            sortable: false,
            defaultsort: false,
            type: 'string',
            mandatory: false,
            visible: false,
            calculated: false,
            header: false,
          },
        ],
      },
    },
  ],
}
