import { components } from '../../../../../src/dpr/types/api'
import { LoadType } from '../../../../../src/dpr/types/UserReports'

const reportTemplateExampleParentChild: components['schemas']['VariantDefinition'] & { loadType: LoadType } = {
  loadType: LoadType.ASYNC,
  id: 'report-template-parent-child-section',
  name: 'Parent-child-section',
  description: 'Template: "parent-child-section". </br> A report with parent and child datasets in sections',
  resourceName: 'reports/list',
  classification: 'OFFICIAL',
  printable: true,
  specification: {
    template: 'parent-child-section',
    sections: ['section1', 'section2'],
    fields: [
      {
        name: 'field1',
        display: 'Field 1',
        sortable: false,
        defaultsort: false,
        type: 'string',
        mandatory: false,
        visible: true,
        calculated: false,
        header: false,
      },
      {
        name: 'childKey',
        display: 'Child key',
        sortable: false,
        defaultsort: false,
        type: 'string',
        mandatory: false,
        visible: true,
        calculated: false,
        header: false,
      },
      {
        name: 'section1',
        display: 'Section 1',
        sortable: false,
        defaultsort: false,
        type: 'string',
        mandatory: false,
        visible: true,
        calculated: false,
        header: false,
      },
      {
        name: 'section2',
        display: 'Section 2',
        sortable: false,
        defaultsort: false,
        type: 'string',
        mandatory: false,
        visible: true,
        calculated: false,
        header: false,
      },
    ],
  },
  childVariants: [
    {
      id: 'report-template-parent-child-section_child',
      name: 'Child Report',
      resourceName: 'reports/list',
      joinFields: ['childKey'],
      specification: {
        sections: [],
        template: 'parent-child',
        fields: [
          {
            name: 'childKey',
            display: 'no shown',
            sortable: false,
            defaultsort: false,
            type: 'string',
            mandatory: false,
            visible: true,
            calculated: false,
            header: false,
          },
          {
            name: 'field1',
            display: 'Child Field 1',
            sortable: false,
            defaultsort: false,
            type: 'string',
            mandatory: false,
            visible: true,
            calculated: false,
            header: false,
          },
          {
            name: 'field2',
            display: 'Child Field 2',
            sortable: false,
            defaultsort: false,
            type: 'string',
            mandatory: false,
            visible: true,
            calculated: false,
            header: false,
          },
        ],
      },
    },
  ],
}

export default reportTemplateExampleParentChild
