import { components } from '../../../../../src/dpr/types/api'
import { LoadType } from '../../../../../src/dpr/types/UserReports'

const reportTemplateExampleParentChild: components['schemas']['VariantDefinition'] & { loadType: LoadType } = {
  loadType: LoadType.ASYNC,
  id: 'report-template-parent-child',
  name: 'Parent-child',
  description: 'Parent-child template',
  resourceName: 'reports/list',
  classification: 'OFFICIAL',
  printable: true,
  specification: {
    template: 'parent-child',
    sections: [],
    fields: [
      {
        name: 'section1',
        display: 'First',
        sortable: false,
        defaultsort: false,
        type: 'string',
        mandatory: false,
        visible: true,
        calculated: false,
        header: false,
      },
      {
        name: 'field1',
        display: 'Second',
        sortable: true,
        defaultsort: true,
        type: 'string',
        mandatory: false,
        visible: true,
        calculated: false,
        header: false,
      },
      {
        name: 'field2',
        display: 'Field 2',
        sortable: true,
        defaultsort: false,
        type: 'string',
        mandatory: false,
        visible: true,
        calculated: false,
        header: false,
      },
      {
        name: 'field3',
        display: 'Field 3',
        sortable: true,
        defaultsort: false,
        type: 'string',
        mandatory: false,
        visible: true,
        calculated: false,
        header: false,
      },
      {
        name: 'field4',
        display: 'Field 4',
        sortable: true,
        defaultsort: false,
        type: 'string',
        mandatory: false,
        visible: true,
        calculated: false,
        header: false,
      },
    ],
  },
  childVariants: [
    {
      id: 'report-template-parent-child_child',
      name: 'Child Report',
      resourceName: 'reports/list',
      joinFields: ['section1'],
      specification: {
        sections: [],
        template: 'parent-child',
        fields: [
          {
            name: 'section1',
            display: 'First',
            sortable: false,
            defaultsort: false,
            type: 'string',
            mandatory: false,
            visible: false,
            calculated: false,
            header: false,
          },
          {
            name: 'field2',
            display: 'Field 2',
            sortable: false,
            defaultsort: false,
            type: 'string',
            mandatory: false,
            visible: true,
            calculated: false,
            header: false,
          },
          {
            name: 'field3',
            display: 'Field 3',
            sortable: false,
            defaultsort: false,
            type: 'string',
            mandatory: false,
            visible: true,
            calculated: false,
            header: false,
          },
          {
            name: 'field4',
            display: 'Field 4',
            sortable: false,
            defaultsort: false,
            type: 'string',
            mandatory: false,
            visible: true,
            calculated: false,
            header: false,
          },
        ],
      },
    },
    {
      id: 'report-template-parent-child_child_2',
      name: 'Child Report 2',
      resourceName: 'reports/list',
      joinFields: ['section1'],
      specification: {
        sections: [],
        template: 'parent-child',
        fields: [
          {
            name: 'section1',
            display: 'First',
            sortable: false,
            defaultsort: false,
            type: 'string',
            mandatory: false,
            visible: false,
            calculated: false,
            header: false,
          },
          {
            name: 'field2',
            display: 'Field 2',
            sortable: false,
            defaultsort: false,
            type: 'string',
            mandatory: false,
            visible: true,
            calculated: false,
            header: false,
          },
          {
            name: 'field3',
            display: 'Field 3',
            sortable: false,
            defaultsort: false,
            type: 'string',
            mandatory: false,
            visible: true,
            calculated: false,
            header: false,
          },
        ],
      },
    },
  ],
}

export default reportTemplateExampleParentChild
