import { components } from 'dpr/types/api'

const reportTemplateExampleRowSectionChildMultiple: components['schemas']['VariantDefinition'] = {
  id: 'report-template-example-row-section-child-multiple',
  name: 'Sectioned Rows + child template (multiple rows)',
  description: 'A report with sectioned rows and child report, with multiple dataset rows',
  resourceName: 'reports/list',
  classification: 'OFFICIAL',
  printable: true,
  specification: {
    template: 'row-section-child',
    sections: ['section1', 'section2', 'section3'],
    fields: [
      {
        name: 'field1',
        display: 'Field One',
        sortable: false,
        defaultsort: false,
        type: 'string',
        mandatory: false,
        visible: true,
        calculated: false,
        header: false,
      },
      {
        name: 'field2',
        display: 'Field Two',
        sortable: false,
        defaultsort: false,
        type: 'string',
        mandatory: false,
        visible: true,
        calculated: false,
        header: false,
      },
      {
        name: 'joinField',
        display: 'Join Field',
        sortable: false,
        defaultsort: false,
        type: 'string',
        mandatory: false,
        visible: false,
        calculated: false,
        header: false,
      },
      {
        name: 'section1',
        display: 'Data columns as rows',
        sortable: false,
        defaultsort: false,
        type: 'string',
        mandatory: false,
        visible: false,
        calculated: false,
        header: false,
      },
      {
        name: 'section2',
        display: 'Child report',
        sortable: false,
        defaultsort: false,
        type: 'string',
        mandatory: false,
        visible: false,
        calculated: false,
        header: false,
      },
      {
        name: 'section3',
        display: 'Child report 2',
        sortable: false,
        defaultsort: false,
        type: 'string',
        mandatory: false,
        visible: false,
        calculated: false,
        header: false,
      },
    ],
  },
  childVariants: [
    {
      id: 'report-template-example-row-section-child-multiple_child',
      name: 'Child Report',
      resourceName: 'reports/list',
      joinFields: ['joinField'],
      specification: {
        sections: [],
        template: 'row-section-child',
        fields: [
          {
            name: 'childField1',
            display: 'Child field 1',
            sortable: false,
            defaultsort: false,
            type: 'string',
            mandatory: false,
            visible: true,
            calculated: false,
            header: false,
          },
          {
            name: 'childField2',
            display: 'Child field 2',
            sortable: false,
            defaultsort: false,
            type: 'string',
            mandatory: false,
            visible: true,
            calculated: false,
            header: false,
          },
          {
            name: 'joinField',
            display: 'Join Field',
            sortable: false,
            defaultsort: false,
            type: 'string',
            mandatory: false,
            visible: false,
            calculated: false,
            header: false,
          },
        ],
      },
    },
    {
      id: 'report-template-example-row-section-child-multiple_child-2',
      name: 'Child Report',
      resourceName: 'reports/list',
      joinFields: ['joinField'],
      specification: {
        sections: [],
        template: 'row-section-child',
        fields: [
          {
            name: 'childField1',
            display: 'Child field 1',
            sortable: false,
            defaultsort: false,
            type: 'string',
            mandatory: false,
            visible: true,
            calculated: false,
            header: false,
          },
          {
            name: 'childField2',
            display: 'Child field 2',
            sortable: false,
            defaultsort: false,
            type: 'string',
            mandatory: false,
            visible: true,
            calculated: false,
            header: false,
          },
          {
            name: 'joinField',
            display: 'Join Field',
            sortable: false,
            defaultsort: false,
            type: 'string',
            mandatory: false,
            visible: false,
            calculated: false,
            header: false,
          },
        ],
      },
    },
  ],
}

export default reportTemplateExampleRowSectionChildMultiple
