import { components } from "src/dpr/types/api";

const reportTemplateExampleRowSectionMultiple: components['schemas']['VariantDefinition'] = {
  id: 'report-template-example-row-section-multiple-rows',
  name: 'Sectioned Rows template (muliple rows)',
  description: 'A report with sectioned rows',
  resourceName: 'reports/list',
  classification: 'OFFICIAL',
  printable: true,
  specification: {
    template: 'row-section',
    sections: ['section1', 'section2', 'section3'],
    fields: [
      {
        name: 'field1',
        display: 'Field One',
        sortable: false,
        defaultsort: false,
        type: 'string',
        mandatory: false,
        visible: true,
        calculated: false,
        header: false,
      },
      {
        name: 'field2',
        display: 'Field Two',
        sortable: false,
        defaultsort: false,
        type: 'string',
        mandatory: false,
        visible: true,
        calculated: false,
        header: false,
      },
      {
        name: 'field3',
        display: 'Field Three',
        sortable: false,
        defaultsort: false,
        type: 'string',
        mandatory: false,
        visible: true,
        calculated: false,
        header: false,
      },
      {
        name: 'field4',
        display: 'Field Four',
        sortable: false,
        defaultsort: false,
        type: 'string',
        mandatory: false,
        visible: true,
        calculated: false,
        header: false,
      },
      {
        name: 'field5',
        display: 'Field Five',
        sortable: false,
        defaultsort: false,
        type: 'string',
        mandatory: false,
        visible: true,
        calculated: false,
        header: false,
      },
      {
        name: 'field6',
        display: 'Field Six',
        sortable: false,
        defaultsort: false,
        type: 'string',
        mandatory: false,
        visible: true,
        calculated: false,
        header: false,
      },
      {
        name: 'section1',
        display: 'Section 1 title',
        sortable: false,
        defaultsort: false,
        type: 'string',
        mandatory: false,
        visible: false,
        calculated: false,
        header: false,
      },
      {
        name: 'section2',
        display: 'Second 2 title',
        sortable: false,
        defaultsort: false,
        type: 'string',
        mandatory: false,
        visible: false,
        calculated: false,
        header: false,
      },
      {
        name: 'section3',
        display: 'Section 3 title',
        sortable: false,
        defaultsort: false,
        type: 'string',
        mandatory: false,
        visible: false,
        calculated: false,
        header: false,
      },
    ],
  },
}

export default reportTemplateExampleRowSectionMultiple
