const mockAgeRange1TableData = [
  {
    ts: { raw: '2025/01/07' },
    establishment_id: { raw: 'MDI' },
    wing: { raw: 'I' },
    age_range_1: { raw: '18-25' },
    age_range_2: { raw: '' },
    religion_code: { raw: '' },
    religion_description: { raw: '' },
    ethnic_code: { raw: '' },
    ethnic_description: { raw: '' },
    nationality_code: { raw: '' },
    nationality_description: { raw: '' },
    cell: { raw: '' },
    age_range_1_18_25: { raw: '' },
    age_range_1_26_34: { raw: '' },
    age_range_1_35_44: { raw: '' },
    age_range_1_45_54: { raw: '' },
    age_range_1_55_64: { raw: '' },
    count: { raw: '6' },
  },
  {
    ts: { raw: '2025/01/07' },
    establishment_id: { raw: 'MDI' },
    wing: { raw: 'I' },
    age_range_1: { raw: '26-34' },
    age_range_2: { raw: '' },
    religion_code: { raw: '' },
    religion_description: { raw: '' },
    ethnic_code: { raw: '' },
    ethnic_description: { raw: '' },
    nationality_code: { raw: '' },
    nationality_description: { raw: '' },
    cell: { raw: '' },
    age_range_1_18_25: { raw: '' },
    age_range_1_26_34: { raw: '' },
    age_range_1_35_44: { raw: '' },
    age_range_1_45_54: { raw: '' },
    age_range_1_55_64: { raw: '' },
    count: { raw: '12' },
  },
  {
    ts: { raw: '2025/01/07' },
    establishment_id: { raw: 'MDI' },
    wing: { raw: 'I' },
    age_range_1: { raw: '35-44' },
    age_range_2: { raw: '' },
    religion_code: { raw: '' },
    religion_description: { raw: '' },
    ethnic_code: { raw: '' },
    ethnic_description: { raw: '' },
    nationality_code: { raw: '' },
    nationality_description: { raw: '' },
    cell: { raw: '' },
    age_range_1_18_25: { raw: '' },
    age_range_1_26_34: { raw: '' },
    age_range_1_35_44: { raw: '' },
    age_range_1_45_54: { raw: '' },
    age_range_1_55_64: { raw: '' },
    count: { raw: '6' },
  },
  {
    ts: { raw: '2025/01/07' },
    establishment_id: { raw: 'MDI' },
    wing: { raw: 'I' },
    age_range_1: { raw: '45-54' },
    age_range_2: { raw: '' },
    religion_code: { raw: '' },
    religion_description: { raw: '' },
    ethnic_code: { raw: '' },
    ethnic_description: { raw: '' },
    nationality_code: { raw: '' },
    nationality_description: { raw: '' },
    cell: { raw: '' },
    age_range_1_18_25: { raw: '' },
    age_range_1_26_34: { raw: '' },
    age_range_1_35_44: { raw: '' },
    age_range_1_45_54: { raw: '' },
    age_range_1_55_64: { raw: '' },
    count: { raw: '2' },
  },
  {
    ts: { raw: '2025/01/07' },
    establishment_id: { raw: 'MDI' },
    wing: { raw: 'I' },
    age_range_1: { raw: '56-54' },
    age_range_2: { raw: '' },
    religion_code: { raw: '' },
    religion_description: { raw: '' },
    ethnic_code: { raw: '' },
    ethnic_description: { raw: '' },
    nationality_code: { raw: '' },
    nationality_description: { raw: '' },
    cell: { raw: '' },
    age_range_1_18_25: { raw: '' },
    age_range_1_26_34: { raw: '' },
    age_range_1_35_44: { raw: '' },
    age_range_1_45_54: { raw: '' },
    age_range_1_55_64: { raw: '' },
    count: { raw: '2' },
  },
]

const mockAgeRange2TableData = [
  {
    ts: { raw: '2025/01/07' },
    establishment_id: { raw: 'MDI' },
    wing: { raw: 'I' },
    age_range_1: { raw: '' },
    age_range_2: { raw: '18-21' },
    religion_code: { raw: '' },
    religion_description: { raw: '' },
    ethnic_code: { raw: '' },
    ethnic_description: { raw: '' },
    nationality_code: { raw: '' },
    nationality_description: { raw: '' },
    cell: { raw: '' },
    age_range_1_18_25: { raw: '' },
    age_range_1_26_34: { raw: '' },
    age_range_1_35_44: { raw: '' },
    age_range_1_45_54: { raw: '' },
    age_range_1_55_64: { raw: '' },
    count: { raw: '2' },
  },
  {
    ts: { raw: '2025/01/07' },
    establishment_id: { raw: 'MDI' },
    wing: { raw: 'I' },
    age_range_1: { raw: '' },
    age_range_2: { raw: '22-29' },
    religion_code: { raw: '' },
    religion_description: { raw: '' },
    ethnic_code: { raw: '' },
    ethnic_description: { raw: '' },
    nationality_code: { raw: '' },
    nationality_description: { raw: '' },
    cell: { raw: '' },
    age_range_1_18_25: { raw: '' },
    age_range_1_26_34: { raw: '' },
    age_range_1_35_44: { raw: '' },
    age_range_1_45_54: { raw: '' },
    age_range_1_55_64: { raw: '' },
    count: { raw: '10' },
  },
  {
    ts: { raw: '2025/01/07' },
    establishment_id: { raw: 'MDI' },
    wing: { raw: 'I' },
    age_range_1: { raw: '' },
    age_range_2: { raw: '30-39' },
    religion_code: { raw: '' },
    religion_description: { raw: '' },
    ethnic_code: { raw: '' },
    ethnic_description: { raw: '' },
    nationality_code: { raw: '' },
    nationality_description: { raw: '' },
    cell: { raw: '' },
    age_range_1_18_25: { raw: '' },
    age_range_1_26_34: { raw: '' },
    age_range_1_35_44: { raw: '' },
    age_range_1_45_54: { raw: '' },
    age_range_1_55_64: { raw: '' },
    count: { raw: '8' },
  },
  {
    ts: { raw: '2025/01/07' },
    establishment_id: { raw: 'MDI' },
    wing: { raw: 'I' },
    age_range_1: { raw: '' },
    age_range_2: { raw: '40-49' },
    religion_code: { raw: '' },
    religion_description: { raw: '' },
    ethnic_code: { raw: '' },
    ethnic_description: { raw: '' },
    nationality_code: { raw: '' },
    nationality_description: { raw: '' },
    cell: { raw: '' },
    age_range_1_18_25: { raw: '' },
    age_range_1_26_34: { raw: '' },
    age_range_1_35_44: { raw: '' },
    age_range_1_45_54: { raw: '' },
    age_range_1_55_64: { raw: '' },
    count: { raw: '5' },
  },
  {
    ts: { raw: '2025/01/07' },
    establishment_id: { raw: 'MDI' },
    wing: { raw: 'I' },
    age_range_1: { raw: '' },
    age_range_2: { raw: '50-59' },
    religion_code: { raw: '' },
    religion_description: { raw: '' },
    ethnic_code: { raw: '' },
    ethnic_description: { raw: '' },
    nationality_code: { raw: '' },
    nationality_description: { raw: '' },
    cell: { raw: '' },
    age_range_1_18_25: { raw: '' },
    age_range_1_26_34: { raw: '' },
    age_range_1_35_44: { raw: '' },
    age_range_1_45_54: { raw: '' },
    age_range_1_55_64: { raw: '' },
    count: { raw: '3' },
  },
]

const mockTotalTableData = [
  {
    ts: { raw: '2025/01/07' },
    establishment_id: { raw: 'MDI' },
    wing: { raw: '' },
    age_range_1: { raw: '' },
    age_range_2: { raw: '' },
    religion_code: { raw: '' },
    religion_description: { raw: '' },
    ethnic_code: { raw: '' },
    ethnic_description: { raw: '' },
    nationality_code: { raw: '' },
    nationality_description: { raw: '' },
    cell: { raw: '' },
    age_range_1_18_25: { raw: '' },
    age_range_1_26_34: { raw: '' },
    age_range_1_35_44: { raw: '' },
    age_range_1_45_54: { raw: '' },
    age_range_1_55_64: { raw: '' },
    count: { raw: '200' },
  },
]

const mockTotalByWingTableData = [
  {
    ts: { raw: '2025/01/07' },
    establishment_id: { raw: 'MDI' },
    wing: { raw: 'I' },
    age_range_1: { raw: '' },
    age_range_2: { raw: '' },
    religion_code: { raw: '' },
    religion_description: { raw: '' },
    ethnic_code: { raw: '' },
    ethnic_description: { raw: '' },
    nationality_code: { raw: '' },
    nationality_description: { raw: '' },
    cell: { raw: '' },
    age_range_1_18_25: { raw: '' },
    age_range_1_26_34: { raw: '' },
    age_range_1_35_44: { raw: '' },
    age_range_1_45_54: { raw: '' },
    age_range_1_55_64: { raw: '' },
    count: { raw: '28' },
  },
]

const mockReligionTableData = [
  {
    ts: { raw: '2025/01/07' },
    establishment_id: { raw: 'MDI' },
    wing: { raw: 'I' },
    age_range_1: { raw: '' },
    age_range_2: { raw: '' },
    religion_code: { raw: 'ATHE' },
    religion_description: { raw: 'Atheist' },
    ethnic_code: { raw: '' },
    ethnic_description: { raw: '' },
    nationality_code: { raw: '' },
    nationality_description: { raw: '' },
    cell: { raw: '' },
    age_range_1_18_25: { raw: '' },
    age_range_1_26_34: { raw: '' },
    age_range_1_35_44: { raw: '' },
    age_range_1_45_54: { raw: '' },
    age_range_1_55_64: { raw: '' },
    count: { raw: '1' },
  },
  {
    ts: { raw: '2025/01/07' },
    establishment_id: { raw: 'MDI' },
    wing: { raw: 'I' },
    age_range_1: { raw: '' },
    age_range_2: { raw: '' },
    religion_code: { raw: 'BUDD' },
    religion_description: { raw: 'Buddhist' },
    ethnic_code: { raw: '' },
    ethnic_description: { raw: '' },
    nationality_code: { raw: '' },
    nationality_description: { raw: '' },
    cell: { raw: '' },
    age_range_1_18_25: { raw: '' },
    age_range_1_26_34: { raw: '' },
    age_range_1_35_44: { raw: '' },
    age_range_1_45_54: { raw: '' },
    age_range_1_55_64: { raw: '' },
    count: { raw: '1' },
  },
  {
    ts: { raw: '2025/01/07' },
    establishment_id: { raw: 'MDI' },
    wing: { raw: 'I' },
    age_range_1: { raw: '' },
    age_range_2: { raw: '' },
    religion_code: { raw: 'CHRST' },
    religion_description: { raw: 'Christian' },
    ethnic_code: { raw: '' },
    ethnic_description: { raw: '' },
    nationality_code: { raw: '' },
    nationality_description: { raw: '' },
    cell: { raw: '' },
    age_range_1_18_25: { raw: '' },
    age_range_1_26_34: { raw: '' },
    age_range_1_35_44: { raw: '' },
    age_range_1_45_54: { raw: '' },
    age_range_1_55_64: { raw: '' },
    count: { raw: '1' },
  },
  {
    ts: { raw: '2025/01/07' },
    establishment_id: { raw: 'MDI' },
    wing: { raw: 'I' },
    age_range_1: { raw: '' },
    age_range_2: { raw: '' },
    religion_code: { raw: 'COFE' },
    religion_description: { raw: 'Church of England (Anglican)' },
    ethnic_code: { raw: '' },
    ethnic_description: { raw: '' },
    nationality_code: { raw: '' },
    nationality_description: { raw: '' },
    cell: { raw: '' },
    age_range_1_18_25: { raw: '' },
    age_range_1_26_34: { raw: '' },
    age_range_1_35_44: { raw: '' },
    age_range_1_45_54: { raw: '' },
    age_range_1_55_64: { raw: '' },
    count: { raw: '8' },
  },
  {
    ts: { raw: '2025/01/07' },
    establishment_id: { raw: 'MDI' },
    wing: { raw: 'I' },
    age_range_1: { raw: '' },
    age_range_2: { raw: '' },
    religion_code: { raw: 'MOS' },
    religion_description: { raw: 'Muslim' },
    ethnic_code: { raw: '' },
    ethnic_description: { raw: '' },
    nationality_code: { raw: '' },
    nationality_description: { raw: '' },
    cell: { raw: '' },
    age_range_1_18_25: { raw: '' },
    age_range_1_26_34: { raw: '' },
    age_range_1_35_44: { raw: '' },
    age_range_1_45_54: { raw: '' },
    age_range_1_55_64: { raw: '' },
    count: { raw: '4' },
  },
  {
    ts: { raw: '2025/01/07' },
    establishment_id: { raw: 'MDI' },
    wing: { raw: 'I' },
    age_range_1: { raw: '' },
    age_range_2: { raw: '' },
    religion_code: { raw: 'NIL' },
    religion_description: { raw: 'No Religion' },
    ethnic_code: { raw: '' },
    ethnic_description: { raw: '' },
    nationality_code: { raw: '' },
    nationality_description: { raw: '' },
    cell: { raw: '' },
    age_range_1_18_25: { raw: '' },
    age_range_1_26_34: { raw: '' },
    age_range_1_35_44: { raw: '' },
    age_range_1_45_54: { raw: '' },
    age_range_1_55_64: { raw: '' },
    count: { raw: '6' },
  },
  {
    ts: { raw: '2025/01/07' },
    establishment_id: { raw: 'MDI' },
    wing: { raw: 'I' },
    age_range_1: { raw: '' },
    age_range_2: { raw: '' },
    religion_code: { raw: 'RC' },
    religion_description: { raw: 'Roman Catholic' },
    ethnic_code: { raw: '' },
    ethnic_description: { raw: '' },
    nationality_code: { raw: '' },
    nationality_description: { raw: '' },
    cell: { raw: '' },
    age_range_1_18_25: { raw: '' },
    age_range_1_26_34: { raw: '' },
    age_range_1_35_44: { raw: '' },
    age_range_1_45_54: { raw: '' },
    age_range_1_55_64: { raw: '' },
    count: { raw: '7' },
  },
]

const mockEthnicTableData = [
  {
    ts: { raw: '2025/01/07' },
    establishment_id: { raw: 'MDI' },
    wing: { raw: 'I' },
    age_range_1: { raw: '' },
    age_range_2: { raw: '' },
    religion_code: { raw: '' },
    religion_description: { raw: '' },
    ethnic_code: { raw: 'A2' },
    ethnic_description: { raw: 'A2-Asian/Asian British: Pakistani' },
    nationality_code: { raw: '' },
    nationality_description: { raw: '' },
    cell: { raw: '' },
    age_range_1_18_25: { raw: '2' },
    age_range_1_26_34: { raw: '2' },
    age_range_1_35_44: { raw: '0' },
    age_range_1_45_54: { raw: '0' },
    age_range_1_55_64: { raw: '0' },
    count: { raw: '4' },
  },
  {
    ts: { raw: '2025/01/07' },
    establishment_id: { raw: 'MDI' },
    wing: { raw: 'I' },
    age_range_1: { raw: '' },
    age_range_2: { raw: '' },
    religion_code: { raw: '' },
    religion_description: { raw: '' },
    ethnic_code: { raw: 'W2' },
    ethnic_description: { raw: 'W1-White: Eng./Welsh/Scot./N.Irish/British' },
    nationality_code: { raw: '' },
    nationality_description: { raw: '' },
    cell: { raw: '' },
    age_range_1_18_25: { raw: '4' },
    age_range_1_26_34: { raw: '10' },
    age_range_1_35_44: { raw: '6' },
    age_range_1_45_54: { raw: '2' },
    age_range_1_55_64: { raw: '2' },
    count: { raw: '24' },
  },
]

const mockCellTableData = [
  {
    ts: { raw: '2025/01/07' },
    establishment_id: { raw: 'MDI' },
    wing: { raw: 'I' },
    age_range_1: { raw: '' },
    age_range_2: { raw: '' },
    religion_code: { raw: '' },
    religion_description: { raw: '' },
    ethnic_code: { raw: '' },
    ethnic_description: { raw: '' },
    nationality_code: { raw: '' },
    nationality_description: { raw: '' },
    cell: { raw: 'I-1-001' },
    age_range_1_18_25: { raw: '' },
    age_range_1_26_34: { raw: '' },
    age_range_1_35_44: { raw: '' },
    age_range_1_45_54: { raw: '' },
    age_range_1_55_64: { raw: '' },
    count: { raw: '1' },
  },
  {
    ts: { raw: '2025/01/07' },
    establishment_id: { raw: 'MDI' },
    wing: { raw: 'I' },
    age_range_1: { raw: '' },
    age_range_2: { raw: '' },
    religion_code: { raw: '' },
    religion_description: { raw: '' },
    ethnic_code: { raw: '' },
    ethnic_description: { raw: '' },
    nationality_code: { raw: '' },
    nationality_description: { raw: '' },
    cell: { raw: 'I-1-002' },
    age_range_1_18_25: { raw: '' },
    age_range_1_26_34: { raw: '' },
    age_range_1_35_44: { raw: '' },
    age_range_1_45_54: { raw: '' },
    age_range_1_55_64: { raw: '' },
    count: { raw: '1' },
  },
  {
    ts: { raw: '2025/01/07' },
    establishment_id: { raw: 'MDI' },
    wing: { raw: 'I' },
    age_range_1: { raw: '' },
    age_range_2: { raw: '' },
    religion_code: { raw: '' },
    religion_description: { raw: '' },
    ethnic_code: { raw: '' },
    ethnic_description: { raw: '' },
    nationality_code: { raw: '' },
    nationality_description: { raw: '' },
    cell: { raw: 'I-1-005' },
    age_range_1_18_25: { raw: '' },
    age_range_1_26_34: { raw: '' },
    age_range_1_35_44: { raw: '' },
    age_range_1_45_54: { raw: '' },
    age_range_1_55_64: { raw: '' },
    count: { raw: '1' },
  },
  {
    ts: { raw: '2025/01/07' },
    establishment_id: { raw: 'MDI' },
    wing: { raw: 'I' },
    age_range_1: { raw: '' },
    age_range_2: { raw: '' },
    religion_code: { raw: '' },
    religion_description: { raw: '' },
    ethnic_code: { raw: '' },
    ethnic_description: { raw: '' },
    nationality_code: { raw: '' },
    nationality_description: { raw: '' },
    cell: { raw: 'I-1-006' },
    age_range_1_18_25: { raw: '' },
    age_range_1_26_34: { raw: '' },
    age_range_1_35_44: { raw: '' },
    age_range_1_45_54: { raw: '' },
    age_range_1_55_64: { raw: '' },
    count: { raw: '1' },
  },
  {
    ts: { raw: '2025/01/07' },
    establishment_id: { raw: 'MDI' },
    wing: { raw: 'I' },
    age_range_1: { raw: '' },
    age_range_2: { raw: '' },
    religion_code: { raw: '' },
    religion_description: { raw: '' },
    ethnic_code: { raw: '' },
    ethnic_description: { raw: '' },
    nationality_code: { raw: '' },
    nationality_description: { raw: '' },
    cell: { raw: 'I-1-007' },
    age_range_1_18_25: { raw: '' },
    age_range_1_26_34: { raw: '' },
    age_range_1_35_44: { raw: '' },
    age_range_1_45_54: { raw: '' },
    age_range_1_55_64: { raw: '' },
    count: { raw: '1' },
  },
  {
    ts: { raw: '2025/01/07' },
    establishment_id: { raw: 'MDI' },
    wing: { raw: 'I' },
    age_range_1: { raw: '' },
    age_range_2: { raw: '' },
    religion_code: { raw: '' },
    religion_description: { raw: '' },
    ethnic_code: { raw: '' },
    ethnic_description: { raw: '' },
    nationality_code: { raw: '' },
    nationality_description: { raw: '' },
    cell: { raw: 'I-1-008' },
    age_range_1_18_25: { raw: '' },
    age_range_1_26_34: { raw: '' },
    age_range_1_35_44: { raw: '' },
    age_range_1_45_54: { raw: '' },
    age_range_1_55_64: { raw: '' },
    count: { raw: '1' },
  },
  {
    ts: { raw: '2025/01/07' },
    establishment_id: { raw: 'MDI' },
    wing: { raw: 'I' },
    age_range_1: { raw: '' },
    age_range_2: { raw: '' },
    religion_code: { raw: '' },
    religion_description: { raw: '' },
    ethnic_code: { raw: '' },
    ethnic_description: { raw: '' },
    nationality_code: { raw: '' },
    nationality_description: { raw: '' },
    cell: { raw: 'I-1-009' },
    age_range_1_18_25: { raw: '' },
    age_range_1_26_34: { raw: '' },
    age_range_1_35_44: { raw: '' },
    age_range_1_45_54: { raw: '' },
    age_range_1_55_64: { raw: '' },
    count: { raw: '1' },
  },
  {
    ts: { raw: '2025/01/07' },
    establishment_id: { raw: 'MDI' },
    wing: { raw: 'I' },
    age_range_1: { raw: '' },
    age_range_2: { raw: '' },
    religion_code: { raw: '' },
    religion_description: { raw: '' },
    ethnic_code: { raw: '' },
    ethnic_description: { raw: '' },
    nationality_code: { raw: '' },
    nationality_description: { raw: '' },
    cell: { raw: 'I-1-010' },
    age_range_1_18_25: { raw: '' },
    age_range_1_26_34: { raw: '' },
    age_range_1_35_44: { raw: '' },
    age_range_1_45_54: { raw: '' },
    age_range_1_55_64: { raw: '' },
    count: { raw: '1' },
  },
  {
    ts: { raw: '2025/01/07' },
    establishment_id: { raw: 'MDI' },
    wing: { raw: 'I' },
    age_range_1: { raw: '' },
    age_range_2: { raw: '' },
    religion_code: { raw: '' },
    religion_description: { raw: '' },
    ethnic_code: { raw: '' },
    ethnic_description: { raw: '' },
    nationality_code: { raw: '' },
    nationality_description: { raw: '' },
    cell: { raw: 'I-1-015' },
    age_range_1_18_25: { raw: '' },
    age_range_1_26_34: { raw: '' },
    age_range_1_35_44: { raw: '' },
    age_range_1_45_54: { raw: '' },
    age_range_1_55_64: { raw: '' },
    count: { raw: '1' },
  },
  {
    ts: { raw: '2025/01/07' },
    establishment_id: { raw: 'MDI' },
    wing: { raw: 'I' },
    age_range_1: { raw: '' },
    age_range_2: { raw: '' },
    religion_code: { raw: '' },
    religion_description: { raw: '' },
    ethnic_code: { raw: '' },
    ethnic_description: { raw: '' },
    nationality_code: { raw: '' },
    nationality_description: { raw: '' },
    cell: { raw: 'I-1-016' },
    age_range_1_18_25: { raw: '' },
    age_range_1_26_34: { raw: '' },
    age_range_1_35_44: { raw: '' },
    age_range_1_45_54: { raw: '' },
    age_range_1_55_64: { raw: '' },
    count: { raw: '1' },
  },
  {
    ts: { raw: '2025/01/07' },
    establishment_id: { raw: 'MDI' },
    wing: { raw: 'I' },
    age_range_1: { raw: '' },
    age_range_2: { raw: '' },
    religion_code: { raw: '' },
    religion_description: { raw: '' },
    ethnic_code: { raw: '' },
    ethnic_description: { raw: '' },
    nationality_code: { raw: '' },
    nationality_description: { raw: '' },
    cell: { raw: 'I-1-017' },
    age_range_1_18_25: { raw: '' },
    age_range_1_26_34: { raw: '' },
    age_range_1_35_44: { raw: '' },
    age_range_1_45_54: { raw: '' },
    age_range_1_55_64: { raw: '' },
    count: { raw: '1' },
  },
  {
    ts: { raw: '2025/01/07' },
    establishment_id: { raw: 'MDI' },
    wing: { raw: 'I' },
    age_range_1: { raw: '' },
    age_range_2: { raw: '' },
    religion_code: { raw: '' },
    religion_description: { raw: '' },
    ethnic_code: { raw: '' },
    ethnic_description: { raw: '' },
    nationality_code: { raw: '' },
    nationality_description: { raw: '' },
    cell: { raw: 'I-1-018' },
    age_range_1_18_25: { raw: '' },
    age_range_1_26_34: { raw: '' },
    age_range_1_35_44: { raw: '' },
    age_range_1_45_54: { raw: '' },
    age_range_1_55_64: { raw: '' },
    count: { raw: '1' },
  },
  {
    ts: { raw: '2025/01/07' },
    establishment_id: { raw: 'MDI' },
    wing: { raw: 'I' },
    age_range_1: { raw: '' },
    age_range_2: { raw: '' },
    religion_code: { raw: '' },
    religion_description: { raw: '' },
    ethnic_code: { raw: '' },
    ethnic_description: { raw: '' },
    nationality_code: { raw: '' },
    nationality_description: { raw: '' },
    cell: { raw: 'I-2-001' },
    age_range_1_18_25: { raw: '' },
    age_range_1_26_34: { raw: '' },
    age_range_1_35_44: { raw: '' },
    age_range_1_45_54: { raw: '' },
    age_range_1_55_64: { raw: '' },
    count: { raw: '1' },
  },
  {
    ts: { raw: '2025/01/07' },
    establishment_id: { raw: 'MDI' },
    wing: { raw: 'I' },
    age_range_1: { raw: '' },
    age_range_2: { raw: '' },
    religion_code: { raw: '' },
    religion_description: { raw: '' },
    ethnic_code: { raw: '' },
    ethnic_description: { raw: '' },
    nationality_code: { raw: '' },
    nationality_description: { raw: '' },
    cell: { raw: 'I-2-002' },
    age_range_1_18_25: { raw: '' },
    age_range_1_26_34: { raw: '' },
    age_range_1_35_44: { raw: '' },
    age_range_1_45_54: { raw: '' },
    age_range_1_55_64: { raw: '' },
    count: { raw: '1' },
  },
  {
    ts: { raw: '2025/01/07' },
    establishment_id: { raw: 'MDI' },
    wing: { raw: 'I' },
    age_range_1: { raw: '' },
    age_range_2: { raw: '' },
    religion_code: { raw: '' },
    religion_description: { raw: '' },
    ethnic_code: { raw: '' },
    ethnic_description: { raw: '' },
    nationality_code: { raw: '' },
    nationality_description: { raw: '' },
    cell: { raw: 'I-2-003' },
    age_range_1_18_25: { raw: '' },
    age_range_1_26_34: { raw: '' },
    age_range_1_35_44: { raw: '' },
    age_range_1_45_54: { raw: '' },
    age_range_1_55_64: { raw: '' },
    count: { raw: '1' },
  },
  {
    ts: { raw: '2025/01/07' },
    establishment_id: { raw: 'MDI' },
    wing: { raw: 'I' },
    age_range_1: { raw: '' },
    age_range_2: { raw: '' },
    religion_code: { raw: '' },
    religion_description: { raw: '' },
    ethnic_code: { raw: '' },
    ethnic_description: { raw: '' },
    nationality_code: { raw: '' },
    nationality_description: { raw: '' },
    cell: { raw: 'I-2-004' },
    age_range_1_18_25: { raw: '' },
    age_range_1_26_34: { raw: '' },
    age_range_1_35_44: { raw: '' },
    age_range_1_45_54: { raw: '' },
    age_range_1_55_64: { raw: '' },
    count: { raw: '1' },
  },
  {
    ts: { raw: '2025/01/07' },
    establishment_id: { raw: 'MDI' },
    wing: { raw: 'I' },
    age_range_1: { raw: '' },
    age_range_2: { raw: '' },
    religion_code: { raw: '' },
    religion_description: { raw: '' },
    ethnic_code: { raw: '' },
    ethnic_description: { raw: '' },
    nationality_code: { raw: '' },
    nationality_description: { raw: '' },
    cell: { raw: 'I-2-005' },
    age_range_1_18_25: { raw: '' },
    age_range_1_26_34: { raw: '' },
    age_range_1_35_44: { raw: '' },
    age_range_1_45_54: { raw: '' },
    age_range_1_55_64: { raw: '' },
    count: { raw: '2' },
  },
  {
    ts: { raw: '2025/01/07' },
    establishment_id: { raw: 'MDI' },
    wing: { raw: 'I' },
    age_range_1: { raw: '' },
    age_range_2: { raw: '' },
    religion_code: { raw: '' },
    religion_description: { raw: '' },
    ethnic_code: { raw: '' },
    ethnic_description: { raw: '' },
    nationality_code: { raw: '' },
    nationality_description: { raw: '' },
    cell: { raw: 'I-2-006' },
    age_range_1_18_25: { raw: '' },
    age_range_1_26_34: { raw: '' },
    age_range_1_35_44: { raw: '' },
    age_range_1_45_54: { raw: '' },
    age_range_1_55_64: { raw: '' },
    count: { raw: '1' },
  },
  {
    ts: { raw: '2025/01/07' },
    establishment_id: { raw: 'MDI' },
    wing: { raw: 'I' },
    age_range_1: { raw: '' },
    age_range_2: { raw: '' },
    religion_code: { raw: '' },
    religion_description: { raw: '' },
    ethnic_code: { raw: '' },
    ethnic_description: { raw: '' },
    nationality_code: { raw: '' },
    nationality_description: { raw: '' },
    cell: { raw: 'I-2-007' },
    age_range_1_18_25: { raw: '' },
    age_range_1_26_34: { raw: '' },
    age_range_1_35_44: { raw: '' },
    age_range_1_45_54: { raw: '' },
    age_range_1_55_64: { raw: '' },
    count: { raw: '1' },
  },
]

const mockNationalityTableData = [
  {
    ts: { raw: '2025/01/07' },
    establishment_id: { raw: 'MDI' },
    wing: { raw: 'I' },
    age_range_1: { raw: '' },
    age_range_2: { raw: '' },
    religion_code: { raw: '' },
    religion_description: { raw: '' },
    ethnic_code: { raw: '' },
    ethnic_description: { raw: '' },
    nationality_code: { raw: 'BRIT' },
    nationality_description: { raw: 'British' },
    cell: { raw: '' },
    age_range_1_18_25: { raw: '' },
    age_range_1_26_34: { raw: '' },
    age_range_1_35_44: { raw: '' },
    age_range_1_45_54: { raw: '' },
    age_range_1_55_64: { raw: '' },
    count: { raw: '28' },
  },
]

const mockAgeBreakdownData = [
  [
    ...mockAgeRange1TableData,
    ...mockAgeRange2TableData,
    ...mockReligionTableData,
    ...mockEthnicTableData,
    ...mockTotalTableData,
    ...mockTotalByWingTableData,
    ...mockCellTableData,
    ...mockNationalityTableData,
  ],
]

export const generateAgeBreakdownData = (establishment: string, wing: string) => {
  let data = [
    ...mockTotalTableData,
    ...mockAgeRange1TableData,
    ...mockAgeRange2TableData,
    ...mockReligionTableData,
    ...mockEthnicTableData,
    ...mockNationalityTableData,
  ]

  if (establishment) {
    data = data.map((d) => {
      return {
        ...d,
        establishment_id: { raw: establishment },
      }
    })
  } else {
    data = data.map((d) => {
      return {
        ...d,
        establishment_id: { raw: 'All' },
      }
    })
  }

  if (wing) {
    data = [...data, ...mockTotalByWingTableData, ...mockCellTableData]
    data = data.map((d) => {
      if (d.wing.raw === '') {
        return d
      }
      return {
        ...d,
        wing: { raw: wing },
      }
    })
  } else {
    data = data.map((d) => {
      return {
        ...d,
        wing: { raw: '' },
      }
    })
  }
  return data
}

export default {
  mockAgeBreakdownData,
  generateAgeBreakdownData,
}
