import { components } from 'src/dpr/types/api'

export const featureTestingInteractiveDownload: components['schemas']['VariantDefinition'] = {
  id: 'feature-testing-interactive-download',
  name: 'Interactive Download Report',
  description: 'This is an interactive report for download testing',
  resourceName: 'reports/list',
  classification: 'OFFICIAL',
  printable: false,
  interactive: true,
  specification: {
    sections: ['field1', 'field2'],
    template: 'list',
    fields: [
      {
        name: 'field1',
        display: 'Field 1',
        sortable: true,
        defaultsort: false,
        fieldSource: 'specfield',
        type: 'string',
        mandatory: false,
        visible: false,
        calculated: false,
        header: false,
      },
      {
        name: 'field2',
        display: 'Field 2',
        sortable: true,
        type: 'string',
        mandatory: false,
        visible: false,
        calculated: false,
        header: false,
        defaultsort: false,
        fieldSource: 'specfield',
      },
      {
        name: 'field3',
        display: 'Field 3',
        sortable: false,
        visible: true,
        type: 'date',
        mandatory: false,
        calculated: false,
        header: false,
        defaultsort: false,
        fieldSource: 'specfield',
        filter: {
          type: 'daterange',
          defaultValue: '2003-02-01 - 2006-05-04',
          mandatory: false,
          interactive: true,
        },
      },
      {
        name: 'field4',
        display: 'Field 4',
        visible: false,
        sortable: false,
        type: 'string',
        calculated: false,
        header: false,
        defaultsort: false,
        fieldSource: 'specfield',
        mandatory: false,
        filter: {
          type: 'autocomplete',
          dynamicOptions: {
            minimumLength: 3,
          },
          staticOptions: [
            { name: 'Fezzick', display: 'Fezzick' },
            { name: 'Inigo Montoya', display: 'Inigo Montoya' },
            { name: 'Prince Humperdink', display: 'Prince Humperdink' },
            { name: 'Princess Buttercup', display: 'Princess Buttercup' },
            { name: 'Westley', display: 'Westley' },
          ],
          mandatory: false,
          interactive: true,
        },
      },
      {
        name: 'field5',
        display: 'Field 5',
        sortable: false,
        type: 'string',
        mandatory: false,
        visible: false,
        calculated: false,
        header: false,
        defaultsort: false,
        fieldSource: 'specfield',
      },
      {
        name: 'field6',
        display: 'Field 6',
        sortable: true,
        type: 'HTML',
        mandatory: true,
        visible: true,
        calculated: false,
        header: false,
        defaultsort: true,
        sortDirection: 'desc',
        fieldSource: 'specfield',
        filter: {
          mandatory: false,
          type: 'text',
          interactive: true,
        },
      },
      {
        name: 'field7',
        display: 'Field 7',
        sortable: false,
        visible: true,
        type: 'date',
        mandatory: false,
        calculated: false,
        header: false,
        defaultsort: false,
        fieldSource: 'paramfield',
      },
      {
        name: 'field8',
        display: 'Field 8',
        sortable: false,
        visible: false,
        type: 'date',
        mandatory: false,
        calculated: false,
        header: false,
        defaultsort: false,
        fieldSource: 'specfield',
        filter: {
          mandatory: false,
          type: 'multiselect',
          staticOptions: [
            { name: 'value8.1', display: 'Value 8.1' },
            { name: 'value8.2', display: 'Value 8.2' },
            { name: 'value8.3', display: 'Value 8.3' },
            { name: 'value8.4', display: 'Value 8.4' },
          ],
          defaultValue: 'value8.2,value8.3',
          interactive: true,
        },
      },
    ],
  },
}
