import { components } from 'src/dpr/types/api'

export const featureTestingEmptyQuery: components['schemas']['VariantDefinition'] = {
  id: 'feature-testing-empty-query',
  name: 'Empty query',
  description: 'No filters or Sort columns',
  resourceName: 'reports/list',
  classification: 'OFFICIAL',
  printable: false,
  specification: {
    sections: [],
    template: 'list',
    fields: [
      {
        name: 'field1',
        display: 'Field 1',
        sortable: false,
        type: 'string',
        mandatory: false,
        visible: true,
        calculated: false,
        defaultsort: false,
        header: false,
      },
      {
        name: 'field2',
        display: 'Field 2',
        sortable: false,
        type: 'string',
        mandatory: true,
        visible: true,
        calculated: false,
        defaultsort: false,
        header: false,
      },
      {
        name: 'field3',
        display: 'Field 3',
        sortable: false,
        visible: true,
        type: 'date',
        mandatory: false,
        calculated: false,
        defaultsort: false,
        header: false,
      },
      {
        name: 'field4',
        display: 'Field 4',
        visible: false,
        sortable: false,
        type: 'string',
        calculated: false,
        defaultsort: false,
        header: false,
        mandatory: false,
      },
      {
        name: 'field5',
        display: 'Field 5',
        sortable: false,
        type: 'string',
        mandatory: false,
        visible: false,
        calculated: false,
        defaultsort: false,
        header: false,
      },
      {
        name: 'field6',
        display: 'Field 6',
        sortable: false,
        type: 'HTML',
        mandatory: false,
        visible: true,
        calculated: false,
        defaultsort: false,
        header: false,
      },
      {
        name: 'field7',
        display: 'Field 7',
        sortable: false,
        visible: true,
        type: 'date',
        mandatory: false,
        calculated: false,
        defaultsort: false,
        header: false,
      },
    ],
  },
}
