import { components } from 'src/dpr/types/api'

export const featureTestingLongHeadings: components['schemas']['VariantDefinition'] = {
  id: 'feature-testing-long-headers',
  name: 'Long column names',
  description: 'Report with long column names',
  resourceName: 'reports/list',
  classification: 'OFFICIAL',
  printable: false,
  specification: {
    sections: [],
    template: 'list',
    fields: [
      {
        name: 'field1',
        display: 'This column will wrap',
        sortable: false,
        type: 'HTML',
        mandatory: false,
        visible: true,
        calculated: false,
        header: false,
        defaultsort: false,
      },
      {
        name: 'field2',
        display: 'Not going to wrap',
        sortable: false,
        type: 'HTML',
        mandatory: false,
        visible: true,
        calculated: false,
        header: false,
        defaultsort: false,
      },
      {
        name: 'field3',
        display: 'This column will also wrap',
        sortable: false,
        type: 'HTML',
        mandatory: false,
        visible: true,
        calculated: false,
        header: false,
        defaultsort: false,
      },
      {
        name: 'field4',
        display: 'This is a wrapping column',
        sortable: false,
        type: 'HTML',
        mandatory: false,
        visible: true,
        calculated: false,
        header: false,
        defaultsort: false,
      },
      {
        name: 'field5',
        display: 'Definitiley going to wrap on next line',
        sortable: false,
        type: 'HTML',
        mandatory: false,
        visible: true,
        calculated: false,
        header: false,
        defaultsort: false,
      },
      {
        name: 'field6',
        display: 'Reeeeeaaallly long column name that never seems to end',
        sortable: false,
        type: 'HTML',
        mandatory: false,
        visible: true,
        calculated: false,
        header: false,
        defaultsort: false,
      },
      {
        name: 'field6',
        display: 'Days to allocation or rejection',
        sortable: false,
        type: 'HTML',
        mandatory: false,
        visible: true,
        calculated: false,
        header: false,
        defaultsort: false,
      },
      {
        name: 'field7',
        display: 'Short column name',
        sortable: false,
        type: 'HTML',
        mandatory: false,
        visible: true,
        calculated: false,
        header: false,
        defaultsort: false,
      },
      {
        name: 'field8',
        display: 'Stay on one line',
        sortable: false,
        type: 'HTML',
        mandatory: false,
        visible: true,
        calculated: false,
        header: false,
        defaultsort: false,
      },
      {
        name: 'field9',
        display: 'Long but table value sets width',
        sortable: false,
        type: 'HTML',
        mandatory: false,
        visible: true,
        calculated: false,
        header: false,
        defaultsort: false,
      },
    ],
  },
}
