import { components } from 'dpr/types/api'

export const featureTestingOrderFilters: components['schemas']['VariantDefinition'] = {
  id: 'feature-testing-filter-order',
  name: 'Filter Order',
  description: '',
  resourceName: 'reports/list',
  classification: 'OFFICIAL',
  printable: false,
  specification: {
    sections: [],
    template: 'list',
    fields: [
      {
        name: 'field1',
        display: 'Field 1',
        sortable: false,
        type: 'HTML',
        mandatory: false,
        visible: true,
        defaultsort: false,
        calculated: false,
        header: false,
        filter: {
          mandatory: false,
          type: 'text',
          index: 2,
        },
      },
      {
        name: 'field2',
        display: 'Field 2',
        sortable: false,
        type: 'HTML',
        mandatory: false,
        visible: true,
        defaultsort: false,
        calculated: false,
        header: false,
        filter: {
          mandatory: false,
          type: 'text',
          index: 0,
        },
      },
      {
        name: 'field3',
        display: 'Field 3',
        sortable: false,
        type: 'HTML',
        mandatory: false,
        visible: true,
        defaultsort: false,
        calculated: false,
        header: false,
        filter: {
          mandatory: false,
          type: 'text',
        },
      },
      {
        name: 'field4',
        display: 'Field 4',
        sortable: false,
        type: 'HTML',
        mandatory: false,
        visible: true,
        defaultsort: false,
        calculated: false,
        header: false,
        filter: {
          mandatory: false,
          type: 'text',
          interactive: true,
          index: 2,
        },
      },
      {
        name: 'field5',
        display: 'Field 5',
        sortable: false,
        type: 'HTML',
        mandatory: false,
        visible: true,
        defaultsort: false,
        calculated: false,
        header: false,
        filter: {
          mandatory: false,
          type: 'text',
          interactive: true,
          index: 0,
        },
      },
      {
        name: 'field6',
        display: 'Field 6',
        sortable: false,
        type: 'HTML',
        mandatory: false,
        visible: true,
        defaultsort: false,
        calculated: false,
        header: false,
        filter: {
          mandatory: false,
          type: 'text',
          interactive: true,
        },
      },
    ],
  },
}
