import { components } from 'src/dpr/types/api'

export const featureTestingValidation: components['schemas']['VariantDefinition'] = {
  id: 'feature-testing-validation',
  name: 'Validation Test',
  description: 'The report is used to test the form validation',
  resourceName: 'reports/list',
  classification: 'OFFICIAL',
  printable: false,
  specification: {
    sections: [],
    template: 'list',
    fields: [
      {
        name: 'field1',
        display: 'Field 1',
        sortable: true,
        defaultsort: true,
        type: 'string',
        mandatory: false,
        visible: true,
        calculated: false,
        header: false,
        filter: {
          type: 'Radio',
          staticOptions: [
            { name: 'value1.1', display: 'Value 1.1' },
            { name: 'value1.2', display: 'Value 1.2' },
            { name: 'value1.3', display: 'Value 1.3' },
          ],
          mandatory: true,
        },
      },
      {
        name: 'field2',
        display: 'Field 2',
        sortable: true,
        type: 'string',
        mandatory: true,
        visible: true,
        calculated: false,
        header: false,
        defaultsort: false,
        fieldSource: 'specfield',
        filter: {
          type: 'Select',
          staticOptions: [
            { name: 'value2.1', display: 'Value 2.1' },
            { name: 'value2.2', display: 'Value 2.2' },
            { name: 'value2.3', display: 'Value 2.3' },
          ],
          mandatory: true,
        },
      },
      {
        name: 'field3',
        display: 'Field 3',
        sortable: false,
        visible: true,
        type: 'date',
        mandatory: false,
        calculated: false,
        header: false,
        defaultsort: false,
        fieldSource: 'specfield',
        filter: {
          type: 'daterange',
          mandatory: true,
        },
      },
      {
        name: 'field4',
        display: 'Field 4',
        visible: false,
        sortable: false,
        type: 'string',
        calculated: false,
        header: false,
        defaultsort: false,
        fieldSource: 'specfield',
        mandatory: false,
        filter: {
          type: 'autocomplete',
          dynamicOptions: {
            minimumLength: 3,
          },
          staticOptions: [
            { name: 'Fezzick', display: 'Fezzick' },
            { name: 'Inigo Montoya', display: 'Inigo Montoya' },
            { name: 'Prince Humperdink', display: 'Prince Humperdink' },
            { name: 'Princess Buttercup', display: 'Princess Buttercup' },
            { name: 'Westley', display: 'Westley' },
          ],
          mandatory: true,
        },
      },
      {
        name: 'field5',
        display: 'Field 5',
        sortable: false,
        type: 'HTML',
        mandatory: false,
        visible: true,
        calculated: false,
        header: false,
        defaultsort: false,
        fieldSource: 'specfield',
        filter: {
          type: 'text',
          mandatory: true,
          pattern: 'Value 6\\.\\d',
        },
      },
      {
        name: 'field6',
        display: 'Field 6',
        sortable: false,
        visible: true,
        type: 'date',
        mandatory: false,
        calculated: false,
        header: false,
        defaultsort: false,
        fieldSource: 'specfield',
        filter: {
          type: 'date',
          mandatory: true,
        },
      },
      {
        name: 'field7',
        display: 'Field 7',
        sortable: false,
        visible: true,
        type: 'date',
        mandatory: false,
        calculated: false,
        header: false,
        defaultsort: false,
        fieldSource: 'specfield',
        filter: {
          type: 'multiselect',
          staticOptions: [
            { name: 'value8.1', display: 'Value 8.1' },
            { name: 'value8.2', display: 'Value 8.2' },
            { name: 'value8.3', display: 'Value 8.3' },
            { name: 'value8.4', display: 'Value 8.4' },
          ],
          mandatory: true,
        },
      },
      //
      {
        name: 'field8',
        display: 'Field 8',
        sortable: true,
        defaultsort: true,
        type: 'string',
        mandatory: false,
        visible: true,
        calculated: false,
        header: false,
        filter: {
          type: 'Radio',
          staticOptions: [
            { name: 'value1.1', display: 'Value 1.1' },
            { name: 'value1.2', display: 'Value 1.2' },
            { name: 'value1.3', display: 'Value 1.3' },
          ],
          mandatory: true,
          interactive: true,
        },
      },
      {
        name: 'field9',
        display: 'Field 9',
        sortable: true,
        type: 'string',
        mandatory: true,
        visible: true,
        calculated: false,
        header: false,
        defaultsort: false,
        fieldSource: 'specfield',
        filter: {
          type: 'Select',
          staticOptions: [
            { name: 'value2.1', display: 'Value 2.1' },
            { name: 'value2.2', display: 'Value 2.2' },
            { name: 'value2.3', display: 'Value 2.3' },
          ],
          mandatory: true,
          interactive: true,
        },
      },
      {
        name: 'field10',
        display: 'Field 10',
        sortable: false,
        visible: true,
        type: 'date',
        mandatory: false,
        calculated: false,
        header: false,
        defaultsort: false,
        fieldSource: 'specfield',
        filter: {
          type: 'daterange',
          mandatory: true,
          interactive: true,
        },
      },
      {
        name: 'field11',
        display: 'Field 11',
        visible: false,
        sortable: false,
        type: 'string',
        calculated: false,
        header: false,
        defaultsort: false,
        fieldSource: 'specfield',
        mandatory: false,
        filter: {
          type: 'autocomplete',
          dynamicOptions: {
            minimumLength: 3,
          },
          staticOptions: [
            { name: 'Fezzick', display: 'Fezzick' },
            { name: 'Inigo Montoya', display: 'Inigo Montoya' },
            { name: 'Prince Humperdink', display: 'Prince Humperdink' },
            { name: 'Princess Buttercup', display: 'Princess Buttercup' },
            { name: 'Westley', display: 'Westley' },
          ],
          mandatory: true,
          interactive: true,
        },
      },
      {
        name: 'field12',
        display: 'Field 12',
        sortable: false,
        type: 'HTML',
        mandatory: false,
        visible: true,
        calculated: false,
        header: false,
        defaultsort: false,
        fieldSource: 'specfield',
        filter: {
          type: 'text',
          mandatory: true,
          pattern: 'Value 6\\.\\d',
          interactive: true,
        },
      },
      {
        name: 'field13',
        display: 'Field 13',
        sortable: false,
        visible: true,
        type: 'date',
        mandatory: false,
        calculated: false,
        header: false,
        defaultsort: false,
        fieldSource: 'specfield',
        filter: {
          type: 'date',
          mandatory: true,
          interactive: true,
        },
      },
      {
        name: 'field14',
        display: 'Field 14',
        sortable: false,
        visible: true,
        type: 'date',
        mandatory: false,
        calculated: false,
        header: false,
        defaultsort: false,
        fieldSource: 'specfield',
        filter: {
          type: 'multiselect',
          staticOptions: [
            { name: 'value8.1', display: 'Value 8.1' },
            { name: 'value8.2', display: 'Value 8.2' },
            { name: 'value8.3', display: 'Value 8.3' },
            { name: 'value8.4', display: 'Value 8.4' },
          ],
          mandatory: true,
          interactive: true,
        },
      },
    ],
  },
}
