import { components } from '../../../../../src/dpr/types/api'
import { LoadType } from '../../../../../src/dpr/types/UserReports'

const reportTemplateExampleListSectionWithSectionCols: components['schemas']['VariantDefinition'] & {
  loadType: LoadType
} = {
  loadType: LoadType.ASYNC,
  id: 'report-template-example-list-section-with-section-cols',
  name: 'List-section - with visible section columns',
  description: 'list-section template',
  resourceName: 'reports/list',
  classification: 'OFFICIAL',
  printable: true,
  specification: {
    template: 'list-section',
    sections: ['section1', 'section2'],
    fields: [
      {
        name: 'field1',
        display: 'Field 1',
        sortable: true,
        defaultsort: true,
        type: 'string',
        mandatory: false,
        visible: true,
        calculated: false,
        header: false,
      },
      {
        name: 'field2',
        display: 'Field 2',
        sortable: true,
        type: 'string',
        mandatory: false,
        visible: true,
        calculated: false,
        header: false,
        defaultsort: false,
      },
      {
        name: 'field3',
        display: 'Field 3',
        sortable: false,
        type: 'date',
        mandatory: false,
        visible: true,
        calculated: false,
        header: false,
        defaultsort: false,
      },
      {
        name: 'field4',
        display: 'Field 4',
        sortable: false,
        type: 'string',
        visible: true,
        calculated: false,
        header: false,
        defaultsort: false,
        mandatory: false,
      },
      {
        name: 'field6',
        display: 'Field 6',
        sortable: false,
        type: 'string',
        mandatory: false,
        calculated: false,
        header: false,
        defaultsort: false,
        visible: false,
      },
      {
        name: 'section1',
        display: 'First',
        sortable: true,
        defaultsort: false,
        type: 'string',
        mandatory: false,
        visible: true,
        calculated: false,
        header: false,
      },
      {
        name: 'section2',
        display: 'Second',
        sortable: true,
        defaultsort: false,
        type: 'string',
        mandatory: false,
        visible: false,
        calculated: false,
        header: false,
      },
    ],
  },
}

export default reportTemplateExampleListSectionWithSectionCols
