name: Publish package

on:
  workflow_dispatch:
    inputs:
      versionType:
        description: 'The semantic version segment to increment'
        required: true
        default: feature
        type: choice
        options:
          - major
          - feature
          - bug

jobs:
  publish-package:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v5
      with:
        node-version: 'lts/*'

    # Ensure npm 11.5.1 or later is installed, to support OIDC publishing
    - name: Update npm
      run: npm install -g npm@latest

    - run: npm ci
    - run: npm run package

    - name: Get version
      id: get-version
      run: |
        CURRENT_VERSION=$(npm view @ministryofjustice/hmpps-digital-prison-reporting-frontend version)
        echo "Current version: $CURRENT_VERSION"
        echo "current_version=$CURRENT_VERSION" >> "$GITHUB_OUTPUT"

    - name: Bump version
      id: bump-version
      uses: christian-draeger/increment-semantic-version@1.1.0
      with:
        current-version: ${{ steps.get-version.outputs.current_version }}
        version-fragment: ${{ inputs.versionType }}

    - name: Set version
      run: sed -i -e 's/Version set by script/${{ steps.bump-version.outputs.next-version }}/' dist/package.json

    - name: Publish
      run: npm publish ./dist --access public

  publish-pages:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - run: npm ci
      - run: npm run docs
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist-docs/dpr/
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4